spring.application.name=EventSphere

spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub
spring.datasource.username=postgres
spring.datasource.password=2966

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=m6rJgDgQ2QfP5vQ4K7d4e9B2d9jL8P0sJr4nQ2wZ8hE=
jwt.expiration=3600000

logging.level.org.springframework.security=DEBUG